/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.aut.ense701.gui;

import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import nz.ac.aut.ense701.gameModel.ActionType;
import nz.ac.aut.ense701.gameModel.Game;
import nz.ac.aut.ense701.gameModel.Item;
import nz.ac.aut.ense701.gameModel.Occupant;
import nz.ac.aut.ense701.main.Main;

/**
 *
 * @author Thi
 */
public class ActivityPopupFrame extends javax.swing.JFrame {

    /**
     * Creates new form ActivityPopupFrame
     */
    private Occupant occupant;
    private JFrame jFrame;
    //private Game game;

    public ActivityPopupFrame() {
        initComponents();
    }

    public ActivityPopupFrame(Occupant occupant, JFrame jFrame) {
        //this.Occupant = occupant;
        this.occupant = occupant;
        this.jFrame = jFrame;
        initComponents();
        this.jFrame.setEnabled(false);
    }

    public Occupant getOccupant() {
        return occupant;
    }

    public void setOccupant(Occupant Occupant) {
        this.occupant = Occupant;
    }

    public JFrame getJframe() {
        return jFrame;
    }

    public void setJframe(JFrame Jframe) {
        this.jFrame = Jframe;
    }

    public void setIconForJLableImage() {

        switch (this.getOccupant().getName()) {
            case "Kiwi":
                picActivitylbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiwi.png")));
                break;
            case "Sandwich":
                picActivitylbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sandwich.png")));
                break;
            case "Apple":
                picActivitylbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apple.jpg")));
                break;
            case "Muesli Bar":
                picActivitylbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Muesli.jpg")));
                break;
            case "Orange Juice":
                picActivitylbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oj.jpg")));
                break;
            case "Trap":
                picActivitylbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trap.jpg")));
                break;
            case "Screwdriver":
                picActivitylbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/screwdriver.jpg")));
                break;
        }
    }

    public void setActivityTextArea(ActionType actiontype) {
        switch (actiontype) {
            case USE:
                if (this.getOccupant().getName().equals("Trap")) {
                    this.activityLbl.setText("You trapped this predator.");
                } else if (this.getOccupant().getName().equals("Screwdriver")) {
                    this.activityLbl.setText("You fixed the broken trap.");
                } else {
                    this.activityLbl.setText("You consumed this " + this.getOccupant().getName());
                }
                break;
            case DROP:
                this.activityLbl.setText("You dropped " + this.getOccupant().toString());
                break;
            case COUNT:
                this.activityLbl.setText("You counted this " + this.getOccupant().toString());
                break;
            case COLLECT:
                this.activityLbl.setText("You collected " + this.getOccupant().toString());
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        picActivitylbl = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        activityLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Activity Message");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(500, 200));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        picActivitylbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        okButton.setFont(new java.awt.Font("ËÎÌו", 1, 12)); // NOI18N
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        activityLbl.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        activityLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(activityLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(picActivitylbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(activityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(picActivitylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.jFrame.setEnabled(true);
    }//GEN-LAST:event_okButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.dispose();
        this.jFrame.setEnabled(true);
        // Make the pnlIsland to get the focus to listen for the subsequent key release event
        Main.gui.getPnlIsland().requestFocusInWindow();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activityLbl;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel picActivitylbl;
    // End of variables declaration//GEN-END:variables
}
