/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.aut.ense701.gui;

import javax.swing.JFrame;
import nz.ac.aut.ense701.main.Main;

/**
 * This window is designed to give hints to player on how to increase the
 * stamina by consuming the counted kiwis.
 *
 * @author ThiEric
 */
public class GiveStaminaInfoDialog extends javax.swing.JDialog {

    /**
     * Creates new form GiveStaminaInfoDialog
     */
    private JFrame jframe;

    public GiveStaminaInfoDialog() {
        initComponents();
    }

    public GiveStaminaInfoDialog(JFrame jframe) {
        this.jframe = jframe;
        initComponents();
        this.jframe.setEnabled(false);
    }

    public JFrame getJframe() {
        return jframe;
    }

    public void setJframe(JFrame jframe) {
        this.jframe = jframe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        introduclbl = new javax.swing.JLabel();
        okBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        introduclbl.setText("<html> <h1 style=\"text-align: center;\">How to recover your stamina</h1> <p style=\"text-align: center;\"> To recover your stamina, you must collect at least 5 or more Kiwis. After that, click \"Increase Stamina\" button to increase your stamina by 50%. </p> </html>");

        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(introduclbl, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(introduclbl, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(okBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * By clicking the 'ok' button, it will re-enable the main frame.
     *
     * @param evt
     */
    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        this.dispose();

        Main.gui.setEnabled(true);
        // Get the focus after the current window is closed.
        Main.gui.requestFocus();
        // Make the pnlIsland to get the focus to listen for the subsequent key release event
        Main.gui.getPnlIsland().requestFocusInWindow();
    }//GEN-LAST:event_okBtnActionPerformed

    /**
     * By closing the window, it will re-enable the main frame.
     *
     * @param evt
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Main.gui.setEnabled(true);
        // Get the focus after the current window is closed.
        Main.gui.requestFocus();
        // Make the pnlIsland to get the focus to listen for the subsequent key release event
        Main.gui.getPnlIsland().requestFocusInWindow();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel introduclbl;
    private javax.swing.JButton okBtn;
    // End of variables declaration//GEN-END:variables
}
