/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.aut.ense701.gui;

import java.awt.GraphicsConfiguration;
import java.awt.HeadlessException;
import javax.swing.JFrame;
import nz.ac.aut.ense701.main.Main;

/**
 *
 * @author ThiEric
 */
public class NotEnoughCountedKiwiDialog extends javax.swing.JFrame {

    /**
     * Creates new form NotEnoughCountedKiwiDialog
     */
    private JFrame jframe;
    private int kiwicount;
    
    
    public JFrame getJframe() {
        return jframe;
    }

    public void setJframe(JFrame jframe) {
        this.jframe = jframe;
    }

    public int getKiwicount() {
        return kiwicount;
    }

    public void setKiwicount(int kiwicount) {
        this.kiwicount = kiwicount;
    }
    
    
    
    public NotEnoughCountedKiwiDialog() {
        initComponents();
    }

    public NotEnoughCountedKiwiDialog(JFrame jframe){
        this.jframe = jframe;
        initComponents();
        this.jframe.setEnabled(false);
    }


    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okjBtn = new javax.swing.JButton();
        messagelbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        okjBtn.setText("OK");
        okjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okjBtnActionPerformed(evt);
            }
        });

        messagelbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        messagelbl.setText("<html><body>\n<p>Not enough Kiwi. At least you need to collect at least 5 Kiwis.</p>\n</body>\n</html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messagelbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okjBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(messagelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(okjBtn)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//By clickng OK button, it should re-enable the Main Frame.
    private void okjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okjBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.jframe.setEnabled(true);
        Main.gui.getPnlIsland().requestFocusInWindow();
    }//GEN-LAST:event_okjBtnActionPerformed
//When the form is closing, it should enable the main Frame.
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.jframe.setEnabled(true);
        Main.gui.getPnlIsland().requestFocusInWindow();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel messagelbl;
    private javax.swing.JButton okjBtn;
    // End of variables declaration//GEN-END:variables
}
